/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "auth": {
        "SignedUpSuccessfully": string;
        "Password attempts exceeded": string;
        "Incorrect username or password.": string;
        "User is not confirmed.": string;
        "Invalid code/session provided.": string;
        "Invalid session for the user, session can only be used once.": string;
        "Attempt limit exceeded, please try after some time.": string;
        "Invalid verification code provided, please try again.": string;
        "Invalid code provided, please request a code again.": string;
        "Password did not conform with policy: Password must have lowercase characters": string;
        "Password did not conform with policy: Password must have uppercase characters": string;
        "Password did not conform with policy: Password must have symbol characters": string;
        "Password did not conform with policy: Password must have numeric characters": string;
        "Password did not conform with policy: Password not long enough": string;
        "Password does not conform with policy: Password must have lowercase characters": string;
        "Password does not conform with policy: Password must have uppercase characters": string;
        "Password does not conform with policy: Password must have symbol characters": string;
        "Password does not conform with policy: Password must have numeric characters": string;
        "Password does not conform with policy: Password not long enough": string;
        "An account with the given email already exists.": string;
        "CheckYourEmailForConfirmationCode": string;
        "PasswordChangedSuccessfully": string;
        "YourConfirmedSuccessfully": string;
        "NewPasswordRequired": string;
        "Group not found.": string;
        "UsernameExistsException": string;
    };
    "validations": {
        "PasswordMatchCognitoRules": string;
        "IsAlphanumericSpaces": string;
        "isAlphanumeric": string;
        "isEmail": string;
        "isNotEmpty": string;
        "ValidPhone": string;
        "minLength": string;
        "maxLength": string;
        "isNumber": string;
        "arrayMinSize": string;
        "pleaseWait": string;
        "isNumberString": string;
        "isEnum": string;
        "isArray": string;
        "HasMimeType": string;
        "IsBucketFile": string;
        "Match": string;
        "InvalidCognitoPassword": string;
        "isUuid": string;
        "isBoolean": string;
        "UserAlreadyExists": string;
        "FailedToCreateCognitoUser": string;
        "FailedToUpdateCognitoUser": string;
        "FailedToDeleteCognitoUser": string;
        "UserNotFound": string;
        "Db": {
            "email_not_unique": string;
            "sub_is_null": string;
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
